# Generated by Django 3.1.7 on 2021-03-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('ebike', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Bike_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0)),
                ('long', models.FloatField(default=0.0)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.bike')),
            ],
        ),
    ]
