# Generated by Django 3.1.7 on 2021-03-23 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0002_auto_20210323_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_position',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
